apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
controlPlane:
  localAPIEndpoint:
    advertiseAddress: 192.168.0.103
    bindPort: 6443
discovery:
  bootstrapToken:
    token: "{{TOKEN}}"
    caCertHashes: 
    - "{{HASH}}"
    apiServerEndpoint: "{{MASTER_API_SERVER}}"

